<?php 
$strings = 
array(
 'Borrado correctamente'=>'Successfully Deleted',
 'Modificado correctamente'=>'Successfully Modified',
 'Inserción realizada con éxito'=>'Successfully Insertion',
 'Error en la modificación'=>'Modification Error',
 'Error en la inserción'=>'Insertion Error',
 'Introduzca un valor'=>'Enter a value',
 'No existe en la base de datos'=>'Does not exists in database',
 'El usuario ya existe'=>'User already exists',
 'login'=>'login',
 'password'=>'password',
 'La contraseña para este usuario es errónea'=>'The password for this user is wrong',
 'El usuario no existe'=>'The user does not exist',
 'Usuario no autenticado'=>'User not authenticated',
 'Usuario'=>'User',
 'Login'=>'Authenticate',
 'Registro'=>'Registry',
 'Ya existe en la base de datos'=>'Already exists in the database',
 'No se ha podido conectar con la base de datos'=>'Could not connect to database',
 'Error en la consulta sobre la base de datos'=>'Error in query on database',
 'El registro no existe'=>'The record does not exist',
 'Insertar Usuario'=>'Insert User',
 'Borrar Usuario'=>'Delete User',
 'Modificar Usuario'=>'Modify User',
 'Consultar Usuario'=>'Query User',
 'Buscar Usuario'=>'Search Usuario',
 'idioma'=>'Language',
 'ESPAÑOL'=>'Spanish',
 'INGLES'=>'English',
 'GALLEGO'=>'Gallaecian',
 'Insertar'=>'Insert',
 'Modificar'=>'Modify',
 'Borrar'=>'Delete',
 'Consultar'=>'Query',
 'Buscar'=>'Search',
 'Mostrar todos'=>'Show All',
 'Detalle'=>'Detail',
 'Portal de Gestión'=>'Management Site',
 'Cerrar Sesión'=>'Close Session',
 'Volver'=>'Back',
 'Error'=>'Error')
;
 ?>
