<?php 
$strings = 
array(
 'Borrado correctamente'=>'Borrado correctamente',
 'Modificado correctamente'=>'Modificado correctamente',
 'Inserción realizada con éxito'=>'Inserción realizada con éxito',
 'Error en la modificación'=>'Error en la modificación',
 'Error en la inserción'=>'Error en la inserción',
 'Introduzca un valor'=>'Introduzca un valor',
 'No existe en la base de datos'=>'No existe en la base de datos',
 'El usuario ya existe'=>'El usuario ya existe',
 'login'=>'login',
 'password'=>'password',
 'La contraseña para este usuario es errónea'=>'La contraseña para este usuario es errónea',
 'El usuario no existe'=>'El usuario no existe',
 'Usuario no autenticado'=>'Usuario no autenticado',
 'Usuario'=>'Usuario',
 'Login'=>'Autenticar',
 'Registro'=>'Registro',
 'Ya existe en la base de datos'=>'Ya existe en la base de datos',
 'No se ha podido conectar con la base de datos'=>'No se ha podido conectar con la base de datos',
 'Error en la consulta sobre la base de datos'=>'Error en la consulta sobre la base de datos',
 'El registro no existe'=>'El registro no existe',
 'Insertar Usuario'=>'Insertar Usuario',
 'Borrar Usuario'=>'Borrar Usuario',
 'Modificar Usuario'=>'Modificar Usuario',
 'Consultar Usuario'=>'Consultar Usuario',
 'Buscar Usuario'=>'Buscar Usuario',
 'idioma'=>'Idioma',
 'ESPAÑOL'=>'Español',
 'INGLES'=>'Ingles',
 'GALLEGO'=>'Gallego',
 'Insertar'=>'Insertar',
 'Modificar'=>'Modificar',
 'Borrar'=>'Borrar',
 'Consultar'=>'Consultar',
 'Buscar'=>'Buscar',
 'Mostrar todos'=>'Mostrar todos',
 'Detalle'=>'Detalle',
 'Portal de Gestión'=>'Portal de Gestión',
 'Cerrar Sesión'=>'Cerrar Sesión',
 'Volver'=>'Volver',
 'Error'=>'Error')
;
 ?>
